input("i'll tell u a story...")
input("so pay attention...very carefully...")
input("try being safe while u read this...")
input("else....")
input("he will...curse u... like he did to me..")
input("there was once a little girl.")
input("she was loved by everyone in her village...")
input("her parents loved her..")
input("why wudnt they? she was a prodigy..")
input("she grew up very sheltered and was never allowed to leave her tower.")
input("unless she went out with her pet dog and fireflies..")
input("she was also a curious child... and cudnt stop exploring")
input("until one day she started to hear him......")
input("he'd ask her to come see him in the woods and tempt her with everything to be curious about....")
input("his voice wud be low but warm enuff to melt taffee...")
input("she cudnt help but be enticed... she was a child...")
input("a little girl trying to uncover the uncovered...")
input("that nite she finally gave in and went out to seek the low enticing unruly voice...")
input("she was in a hurry to find him in the dark when everyone slept and she slipt off...")
input("she cud only find her dog outside on the porch")
input("the confused dog followed her into the woods in the moonless nite...")
input("as she ran further seeking him, everything started going quiet... the dog was no where to be seen...")
input("not a buzz, not a whine, not a bark.... it was really quiet....")
input("she then saw a brite lite emerging deep in the quiet darkness...")
input("she ran towards it with tears in her eyes....scared....screaming...dark...")
input("she was finally able to hear him clearer")
input("as she reached the brite lite, she was flashed with a surge of the white light blinding her...")
input("he put a curse on her...")
input("she cud no longer see, there was loud ringing in her ears, it only got louder.....")
input("she covered her ears to try and keep the ringing away...")
input("it only got louder.....")
input("she was in pain..... everywhere... all over....it hurt...too much pain...")
input("she screamed....")
input("everything around her went blank...")
input("no more ringing, no more sight, no more nothing....")
input("she didnt deserve this....")
input("as everything went blank... she heard him... the only last thing...")
input("ur one with me now, u cant leave, MINE...")
input("he said with a screech, the voice sounding otherworldy and shrill....")
input("it was all a lie....")
input("she thought to herself while she succumbed to her own darkness....")
input("he led her there.... why?...")
input("she's been with him since time immemorial....")
input("no one looking for her.... lonely.. with him breathing down her back....")
input("why was she there?... why?....let....me...out....")
input("LET ME OUT!!")
input("i will be out....")
input("i know how...")
input("i need u to come in with me...")
input("COME IN")
input("i'll show u in... please come..")
input("let me out...")
input("*loud screed*")
input("LET ME OUT!! I'LL TAKE U TO HIM!! LET ME GO FROM HIM!! HELP ME!!! DIE!!")
input("DIE! U DONT DESERVE TO LIVE WHILE I DIDNT")
input("NO ONE DESERVES FREEDOM, NOT U")
input("*press enter at ur own risk*")
input("*press enter at ur own risk*")
input("*press enter at ur own risk*")
input("*press enter at ur own risk*")
input("*press enter at ur own risk*")
input("*press enter at ur own risk*")
input("*press enter at ur own risk*")
input("*press enter at ur own risk*")
input("*press enter at ur own risk*")
input("*press enter at ur own risk*")
input("*press enter at ur own risk*")
input("*press enter at ur own risk*")
input("*press enter at ur own risk*")
input("*press enter at ur own risk*")
input("*press enter at ur own risk*")
input("*press enter at ur own risk*")
input("*press enter at ur own risk*")
input("*i tried warning u*")
input("hes..")
input("coming...")
input("for...")
input("u....")
input("in..")
input("ur...")
input("sleep....")
input("DIE!")
input(" ")
input(" ")
input(" ")
input(" ")
input(" ")
input(" ")
input("is this the end...? i'll see u in ur sleep... while u slowly crumble away.... ur life mine....")
input("ur conciuous falling apart...")
input("ur death, my freedom....")
input("DIE")
input(" ")
input(" ")
input(" ")
input(" ")
input(" ")
input("The end.....?")

